---
abstract: 'Perl module to manage the PDF imposition'
author:
  - 'Marco Pessotto <melmothx@gmail.com>'
build_requires:
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-Imposition
no_index:
  directory:
    - t
    - inc
requires:
  CAM::PDF: 1.58
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  Module::Load: 0
  PDF::API2: 2.019
  Pod::Usage: 0
  perl: 5.010001
resources:
  repository: https://gitorious.org/perl-pdf-imposition
version: 0.07
